/**
 * Fake Store API
 * A simple e-commerce API for demonstration purposes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FakeStoreApi);
  }
}(this, function(expect, FakeStoreApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FakeStoreApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('productsCategoriesGet', function() {
      it('should call productsCategoriesGet successfully', function(done) {
        //uncomment below and update the code to test productsCategoriesGet
        //instance.productsCategoriesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('productsGet', function() {
      it('should call productsGet successfully', function(done) {
        //uncomment below and update the code to test productsGet
        //instance.productsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('productsIdGet', function() {
      it('should call productsIdGet successfully', function(done) {
        //uncomment below and update the code to test productsIdGet
        //instance.productsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('productsPost', function() {
      it('should call productsPost successfully', function(done) {
        //uncomment below and update the code to test productsPost
        //instance.productsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
