/**
 * Fake Store API
 * A simple e-commerce API for demonstration purposes
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import NewProduct from './model/NewProduct';
import Product from './model/Product';
import ProductRating from './model/ProductRating';
import DefaultApi from './api/DefaultApi';


/**
* A simple e-commerce API for demonstration purposes.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FakeStoreApi = require('index'); // See note below*.
* var xxxSvc = new FakeStoreApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FakeStoreApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FakeStoreApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FakeStoreApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The NewProduct model constructor.
     * @property {module:model/NewProduct}
     */
    NewProduct,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductRating model constructor.
     * @property {module:model/ProductRating}
     */
    ProductRating,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
